# frozen_string_literal: true

require_relative 'dev_session/automatic_archive_test'
require_relative 'dev_session/lifecycle_commands_test'
require_relative 'dev_session/fork_receipts_test'
require_relative 'dev_session/fork_recovery_test'
require_relative 'dev_session/session_resolution_test'
require_relative 'dev_session/session_initialization_test'
require_relative 'dev_session/session_recovery_test'
require_relative 'dev_session/tracking_test'
require_relative 'dev_session/worktrees_test'
require_relative 'dev_session/deletion_lifecycle_test'
require_relative 'dev_session/deletion_recovery_test'
require_relative 'dev_session/deletion_safety_test'
require_relative 'dev_session/lifecycle_archive_test'
require_relative 'dev_session/tmux_identity_test'
require_relative 'dev_session/tmux_runtime_test'
require_relative 'dev_session/codex_runtime_test'
require_relative 'dev_session/archive_test'
require_relative 'dev_session/revive_test'
require_relative 'dev_session/retained_tracking_test'
