# frozen_string_literal: true

require_relative 'workspace_host/registry_extensions_test'
require_relative 'workspace_host/services_registration_test'
require_relative 'workspace_host/commands_and_locks_test'
require_relative 'workspace_host/profile_transition_test'
require_relative 'workspace_host/suspension_test'
